# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05a59bf0b0bf6a90b579109dcf847dad9c1c6be52a1ac99bdafcf54c6fdddffa1ef64758200a6020602a02125a5f933ec1030ce0b9390d4f504ae2ba53007244

test:
  secret_key_base: 55c90a75a455e9c653772b003a35cf749d98a8573c0e55c3241d15e9923b3bfaa84583bfc167a0dae9ec644b44b7ea878725fb2fb9de1663fe9ea30358e77d35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
